micronaut:
  application:
    name: helloWorld
  server:
    port: 8086
  max: 50
kafka:
  bootstrap:
    servers: localhost:9092

datasources:
  default:
    url: jdbc:oracle:thin:@localhost:1521/orclpdb
    username: EDAREST
    password: gogreen
    driverClassName: oracle.jdbc.driver.OracleDriver
#    minPoolSize: 1
#    maxPoolSize: 10
#    connectionFactoryClassName: oracle.ucp.jdbc.PoolXADataSource
#    jpa.default.properties.hibernate.hbm2ddl.auto: update
jpa:
  default:
    entity-scan:
      classpath: true
      packages:
        - 'com.cts.eda.mnt.domain.token'
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true
        dialect: org.hibernate.dialect.Oracle12cDialect
