micronaut:
  application:
    name: edaRest
  server:
    port: 8086
  max: 50
kafka:
  bootstrap:
    servers: localhost:9092

datasources:
  default:
    url: jdbc:oracle:thin:@localhost:1521/orclpdb
    username: EDAREST
    password: gogreen
    driverClassName: oracle.jdbc.driver.OracleDriver
jpa:
  default:
    entity-scan:
      packages:
        - 'com.cts.eda.mnt.domain.token'
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true
        dialect: org.hibernate.dialect.Oracle12cDialect
